export const DEFAULT_DELIVERY_REMINDER_DURATION_MINUTES = 60;
export const DEFAULT_DELIVERY_REMINDER_OFFSET_MINUTES = 15;
export const DEFAULT_FALLBACK_DELIVERY_DELAY_MINUTES = 60;
export const CALENDAR_EVENT_TITLE_PREFIX = 'Grovy delivery reminder';
